version: '3.9'

volumes:
  mysql-data:


networks:
  wordpress:


services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME:-wp}
      MYSQL_USER: ${DB_USER:-wp}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wp}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-Wp123}
      SERVICE_TAGS: ${WP_ENV:-development}
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - wordpress

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    depends_on:
      - mysql
    volumes:
      - ./.ma/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - wordpress

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    environment:
      - DOMAIN=wordpress.localhost  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    depends_on:
      - wordpress
      - mysql
    networks:
      - wordpress

  composer:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/
    depends_on:
      - wordpress
    networks:
      - wordpress

  wp:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - wordpress
      - composer
    networks:
      - wordpress
    command: |
      bash -c '
      
      '

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-Wp123}
    networks:
      - wordpress

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - wordpress